print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "D:/Unity/Projects/Project_Draper_Industries/Assets/Monitor.mb"`)
{
	file -o "D:/Unity/Projects/Project_Draper_Industries/Assets/Monitor.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/Unity/Projects/Project_Draper_Industries/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"D:\\Unity\\Projects\\Project_Draper_Industries\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "D:/Unity/Projects/Project_Draper_Industries/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
